name: ci

on: push
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9", "3.10", "3.11", "3.12"]

        steps:
            - name: Baixar repositório
              uses: actions/checkout@v4

            - name: Instalar o Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{matrix.python-version}}

            - name: Install de libs
              run: pip install -r requirements.txt

            - name: Rodar testes
              run: pytest tests/test_contrato.py